### PR TITLE
Adding own blog (#76)

### PR DESCRIPTION
**Pull request by hxchua**
projectosyo.wix.com/datadoubleconfirm

### CODE REVIEW

**Comment by rushter** [comment]
> We Looked Everywhere
> For This Page!
> (Error 404)

**Comment by hxchua** [comment]
Hi Artem,

So sorry, am still pretty new to Github. Can I check if the issue lies in
my commit? From what I can see, I've managed to add my site in the "README"
file. Or do you mean there's something wrong with my link? Thank you for
your help!

[image: Inline image 1]
Best regards,
Hui

**Comment by rushter** [comment]
`Data Double Confirm https://projectoyo.wixsite.com/datadoubleconfirm [(RSS)](https://projectosyo.wixsite.com/datadoubleconfirm/feed.xml)`

The site you provided doesn't work for me.

**Comment by hxchua** [comment]
Hi Artem,

I realised there's a typo. Should be
https://projectosyo.wixsite.com/datadoubleconfirm. I'm missing an 's'. Will
fix it. Sorry for the trouble.

Best regards,
Hui

**Pull request merged**
